// auto generated by llm
const content = `<note>
🎙️: That late-race spin cost you the podium—how are you feeling?  
🏎️ Max Verstappen: Frustrated, man. I pushed too hard, the car snapped, and my mistake just flared up out of nowhere.  

flare — 突然爆发；snap — 失控打滑  
</note>

<note>
🎙️: You were chasing the leader for twenty laps. What was going through your head?  
🏎️ Lewis Hamilton: I kept telling myself, “Don’t drown in the pressure—just breathe and chase clean.” It didn’t work today, but I’ll be back.  

drown — 淹没；chase — 追赶  
</note>

<note>
🎙️: Your teammate’s strategy seemed to go against yours. Any tension on the radio?  
🏎️ Lando Norris: Not really. We both want to win, so a bit of banter is expected. I’ll buy him a pizza and we’ll laugh it off.  

go against — 与…相反；banter — 打趣  
</note>

<note>
🎙️: The conditions were extreme out there—how did you keep the car on track?  
🏎️ Carlos Sainz: I just treated it like a rainy Sunday back home: smooth hands, no sudden moves, and loads of patience.  

extreme — 极端的；smooth hands — 方向盘握稳  
</note>

<note>
🎙️: You retired early—what happened?  
🏎️ Daniel Ricciardo: Something smelled like fuel, then the engine coughed. I’d love one additional lap, but today the car said “nope.”  

fuel — 燃油；additional — 额外的  
</note>

<note>
🎙️: Your first win—who do you dedicate it to?  
🏎️ George Russell: My mum, my trainer, every kid watching who thinks they don’t resemble a “typical” racer. This one’s for them.  

dedicate — 献给；resemble — 像  
</note>

<note>
🎙️: The team stayed calm under that long safety car. How vital was that?  
🏎️ Charles Leclerc: Huge. They kept me updated and I tried to commend them over the radio—those guys never get enough credit.  

commend — 表扬；credit — 认可  
</note>
---
<note>
🎙️: Max, you just lost the win on the last lap—how do you compose yourself after that?  
🏎️ Max Verstappen: I don’t. I’m furious. One stupid splash of rain and the whole race slips away.  

compose — 使冷静;slips away — 溜走  
</note>

<note>
🎙️: Lewis, another record today—do you feel you’ve finally proved your destiny is at the top?  
🏎️ Lewis Hamilton: Records are cool, but the real buzz is showing kids from nowhere that crazy dreams can happen.  

destiny — 命运;buzz — 兴奋感  
</note>

<note>
🎙️: Lando, you were shouting on the radio about the safety car—why so angry?  
🏎️ Lando Norris: I’m not arrogant, mate, but when you’re blind to the obvious, it feels like the race is stolen from you.  

arrogant — 傲慢的;blind — 视而不见的  
</note>

<note>
🎙️: Daniel, retirement again—any chance you’ll sign a new contract next year?  
🏎️ Daniel Ricciardo: If the right opportunity shows up, sure. Otherwise I’ll just keep smiling and flipping plastic cups at home.  

contract — 合同;plastic — 塑料的  
</note>

<note>
🎙️: Charles, you clipped the wall and ended your race—what went through your mind?  
🏎️ Charles Leclerc: One heartbeat of panic and my whole weekend is in the bin. I still believe I can accomplish big things, just not today.  

accomplish — 完成;heartbeat — 一瞬间  
</note>

<note>
🎙️: George, the team told you to hold position—did you want an intervention from the boss?  
🏎️ George Russell: I want a fair fight, not a babysitter. This is my career on the line, not a playground.  

intervention — 干预;career — 职业生涯  
</note>
---
<note>
🎙️: Max, you finally got the win today—how does it feel?  
🏎️ Max Verstappen: It feels right. I don’t shout about it, but I believe I deserve this after the last few rough Sundays.  

deserve — 应得;rough — 艰难的  
</note>

<note>
🎙️: You seemed upset on the radio when the team kept you out—what happened?  
🏎️ Charles Leclerc: I rely on them for the big calls, but today it felt like we were sailing in a storm with no compass.  

rely — 依赖;sailing — 航行;storm — 暴风雨  
</note>

<note>
🎙️: Lewis, you came from last to podium—how did you keep your head?  
🏎️ Lewis Hamilton: I just told myself, “Fulfill the laps, one by one.” The crowd’s affection kept me going, too.  

fulfill — 完成;affection — 喜爱  
</note>

<note>
🎙️: Lando, you and Oscar were side-by-side for ages—any tension?  
🏎️ Lando Norris: Nah, it was all smiles. I’m not going to accuse my teammate; we both wanted it, that’s sport.  

accuse — 指责  
</note>

<note>
🎙️: You retired after the touch with the wall—what went through your mind?  
🏎️ Daniel Ricciardo: Instant frustration. I wanted to protest to the wall, but it won’t listen. Just one of those days that can strike anytime.  

protest — 抗议;strike — 突然发生  
</note>
---
<note>
🎙️: Max, that last-lap move looked massive on TV—what was going through your head?  
🏎️ Max Verstappen: I saw the gap and didn’t hesitate; either you go for it or you layoff and regret it forever.  

massive — 巨大的;hesitate — 犹豫;layoff — 松手、放弃
</note>

<note>
🎙️: Lewis, from a fan’s standpoint, today felt like a movie—how do you sum it up?  
🏎️ Lewis Hamilton: It was wild out there; I had to gather every bit of calm when the rain came down so drastically.  

standpoint — 立场、角度;gather — 聚集、收拢;drastically — 急剧地
</note>

<note>
🎙️: Lando, you were smiling even after the spin—was that intentional humor or just nerves?  
🏎️ Lando Norris: A bit of both; if you can’t laugh you’ll cry, and I didn’t want the moment to enchant the whole day.  

intentional — 故意的;enchant — 使着迷、缠住
</note>

<note>
🎙️: Carlos, the team’s call left you behind your teammate—are you hesitant to question them on air?  
🏎️ Carlos Sainz: I’m not hesitant at all; we’ll talk in private, but right now I just need to vent a little.  

hesitant — 犹豫的
</note>

<note>
🎙️: Daniel, you retired early—any positives you can take from today?  
🏎️ Daniel Ricciardo: Yeah, I got to see the race from the wall and chat with various fans; sometimes that cheers you up more than points.  

various — 各种各样的
</note>
---
<note>
🎙️: That last-lap spin looked scary—how did you keep it together?  
🏎️ Max Verstappen: I just stared at the wall in my peripheral vision and told myself, “Don’t overreact.” Worked, I guess.  

peripheral — 外围视野;keep it together — 保持镇定  
</note>

<note>
🎙️: You’ve added another win in the rain—what’s your secret?  
🏎️ Lewis Hamilton: I treat every wet lap like an accessory to the story I’m writing; it has to fit perfectly or it ruins the whole look.  

accessory — 配饰，这里比喻为“点缀”;wet lap — 雨中的圈速  
</note>

<note>
🎙️: You seemed to visit the pits every five minutes—tough day?  
🏎️ Lando Norris: Yeah, the safety car was more frequent than my coffee breaks; I nearly asked the vendor for a latte each time I stopped.  

frequent — 频繁的;vendor — 小贩  
</note>

<note>
🎙️: Your teammate was right behind you—any worries?  
🏎️ Daniel Ricciardo: None. I just integrate a little Aussie humor on the radio and it keeps the mood light; he laughs, I maintain the gap.  

integrate — 融入;maintain — 保持  
</note>

<note>
🎙️: The car felt off after that early bump—what happened?  
🏎️ Charles Leclerc: We lost the hybrid architecture, so the power just died. My only capability left was to park it and wave—super frustrating.  

architecture — 结构;capability — 能力  
</note>

<note>
🎙️: You gambled on staying out—do you still believe in that concept?  
🏎️ Carlos Sainz: Yeah, the concept made sense, but the benefit vanished when the sky opened. Next time I’ll pack an umbrella, at least.  

concept — 概念;benefit — 好处  
</note>
---
<note>
🎙️: Max, that last-lap move was wild!  
🏎️ Max Verstappen: Wild? It was torture waiting behind him for ten laps; I’m just glad I didn’t wreck both of us.  

torture — 折磨;wreck — 撞毁  
</note>

<note>
🎙️: Lewis, the team called you in early; did that feel weird?  
🏎️ Lewis Hamilton: A bit weird, yeah, but you roll with it. I’ll ask for a further chat tonight, no drama.  

weird — 奇怪的;further — 进一步的  
</note>

<note>
🎙️: Lando, you were yelling on the radio about the back-marker.  
🏎️ Lando Norris: He totally tried to impede me, cost me a second. Slight smile now, but at the time I wanted to bite the steering wheel.  

impede — 妨碍;slight — 轻微的;bite — 咬  
</note>

<note>
🎙️: Charles, race ended behind the safety car—frustrating?  
🏎️ Charles Leclerc: Frustrating is polite. Furthermore, we need to look at the rules; today felt like a robbery.  

furthermore — 此外  
</note>

<note>
🎙️: George, you spun and still finished P7—how?  
🏎️ George Russell: Just kept my head down after the spin. The transition from wet to dry was tricky, but we survived.  

transition — 过渡  
</note>
---
<note>
🎙️: Max, you seemed furious on the radio after the last stop.  
🏎️ Max Verstappen: I’m not gonna complain on TV, but we had a clear plan and then they swapped me to softs—totally bottled it.  

bottle — 搞砸；complain — 抱怨  
</note>

<note>
🎙️: Lewis, you came from last to the podium—how did you keep your head?  
🏎️ Lewis Hamilton: The race felt like a long transit, but I just kept talking to myself: “Don’t sweat the small stuff, stay present.”  

transit — 过渡；sweat — 焦虑、出汗  
</note>

<note>
🎙️: Lando, you missed Q3 by two-hundredths—what happened?  
🏎️ Lando Norris: I hit a damp patch and the car went all twitchy; those transient slides are impossible to catch. I’ll qualify better tomorrow, promise.  

transient — 短暂的；qualify — 取得资格  
</note>

<note>
🎙️: You retired on lap eight—any early thoughts?  
🏎️ Charles Leclerc: We had a sudden power shortage, no warning. I’ll head back to the garage shortly and figure it out with the guys.  

shortage — 短缺；shortly — 马上  
</note>

<note>
🎙️: Daniel, you joked about bringing your own energy drink—care to explain?  
🏎️ Daniel Ricciardo: Yeah, the budget’s tight this year, so if someone hands me a bottle on the podium, it might just be tap water with glitter!  

budget — 预算；bottle — 瓶子  
</note>
---
<note>
🎙️: Max, that was a nail-biter at the end—how did you keep it together?  
🏎️ Max Verstappen: Honestly, I just told myself, “Don’t screw it up now.” The gap was super tight, but we held on.  

screw — 搞砸;tight — 非常接近的  
</note>

<note>
🎙️: Lando, you were laughing on the radio after that spin—what happened?  
🏎️ Lando Norris: I went wide, hit the wet bit, and suddenly I was doing ballet. My pride’s headed straight to the landfill, but hey, we’ll bounce back.  

landfill — 垃圾填埋场（自嘲“颜面扫地”）  
</note>

<note>
🎙️: Lewis, the rain changed everything today. How did you adapt so quickly?  
🏎️ Lewis Hamilton: You’ve got to digest the conditions lap by lap. I kept pushing for consistency, not hero laps, and it paid off in the end.  

digest — 消化（这里指“适应”）;consistency — 稳定性  
</note>

<note>
🎙️: Charles, the team called you in early and it didn’t work out—any frustration?  
🏎️ Charles Leclerc: A bit, yeah. I thought we could advance further on the old set, but they saw data I didn’t. We’ll talk it through and move on.  

advance — 推进、延长  
</note>

<note>
🎙️: Daniel, you clipped the wall and had to retire—what went through your mind?  
🏎️ Daniel Ricciardo: Just… “Ah, mate, you’ve gotta be kidding me.” I tried to budge past the car ahead, mis-judged by a whisker, and now my weekend luggage is a pair of broken wishbones.  

bud — 微微移动;luggage — 行李（幽默指“带回维修区的破损零件”）  
</note>
---
<note>
🎙️: You snatched the win on the very last lap—how does that feel?  
🏎️ Max Verstappen: It feels unreal. I didn’t expect the race to flip in my favor, but I’ll take it and push forward.  

flip — 突然转变;push forward — 继续前进  
</note>

<note>
🎙️: The crowd was clearly cheering for you; did that give you an extra lift?  
🏎️ Lewis Hamilton: Absolutely. Their loyalty means the world, and I race to represent every single one of them.  

loyalty — 忠诚;represent — 代表  
</note>

<note>
🎙️: You were leading, then the rain came and the team kept you out—any frustration?  
🏎️ Charles Leclerc: A bit, yeah. The call didn’t favor me today, but we’ll talk it through and come back stronger.  

favor — 有利于;come back stronger — 以更强势头回归  
</note>

<note>
🎙️: You’ve had a rough season; what keeps you motivated?  
🏎️ Daniel Ricciardo: Every weekend feels like a new chapter in this crazy saga. I just smile, reset, and drive my heart out.  

saga — 传奇故事;reset — 重新调整  
</note>

<note>
🎙️: You’re heading overseas for the next triple-header; how do you stay sharp?  
🏎️ Lando Norris: I keep the mood light with the guys, but my focus turns towards the renewal of energy once we’re abroad.  

towards — 朝向;renewal — 恢复;abroad — 在国外  
</note>

<note>
🎙️: Your teammate says you two bring out the best in each other—agree?  
🏎️ George Russell: For sure. We keep it respectful on track, and that broad respect helps the whole team move forward.  

broad — 广泛的;move forward — 向前推进  
</note>

<note>
🎙️: Any message for the fans who traveled all the way here?  
🏎️ Carlos Sainz: Huge thanks. You guys are the best representative of passion, and you make every lap feel special.  

representative — 典型代表;make every lap feel special — 让每一圈都意义非凡  
</note>
---
<note>
🎙️: Max, you clipped the grass and still kept the lead—how?  
🏎️ Max Verstappen: The grassy bit was super slippery, but I just kept my foot in. No snappy moves, just smooth.  

grass — 草地;grassy — 长满草的;snappy — 突然的、敏捷的  
</note>

<note>
🎙️: Lewis, second place again—any frustration?  
🏎️ Lewis Hamilton: Definitely a bit marginal today; we’ll debrief and come back stronger.  

definitely — 肯定地;marginal — 勉强的、微小的  
</note>

<note>
🎙️: Lando, your maiden win at last—how does the podium feel?  
🏎️ Lando Norris: Unreal! I almost swallowed a grasshopper on the cool-down lap, but who cares—this pod is mine!  

maiden — 首次的;pod — 领奖台;grasshopper — 蚱蜢  
</note>

<note>
🎙️: Charles, retirement on lap one—what happened?  
🏎️ Charles Leclerc: Someone squeezed me onto the grass, I spun, and that was it. I’ll be feeling this one indefinitely.  

indefinitely — 无限期地;grass — 草地  
</note>

<note>
🎙️: Daniel, five-second penalty for cutting the chicane—fair?  
🏎️ Daniel Ricciardo: Yeah, I knew it the moment I went over the grass. Bit of a snappy decision, but we’ll take it on the chin.  

penalty — 处罚;grass — 草地;snappy — 迅速的  
</note>
---
<note>
🎙️: Max, you just took the win—how does it feel?  
🏎️ Max Verstappen: Relieved, mate. I saw a few drops on my visor and thought, “Don’t get cocky, just bring it home.”  

relieved — 如释重负的；a few — 几滴  
</note>

<note>
🎙️: Lewis, you spun on the damp track—what happened?  
🏎️ Lewis Hamilton: I was aware the surface was changing, but I still leaned on it like it was dry. Totally my bad.  

aware — 意识到的；dry — 干燥的  
</note>

<note>
🎙️: Lando, P3 after that crazy restart—happy?  
🏎️ Lando Norris: Buzzing! I treated the last lap like a rental kart—just sent it and prayed.  

rental — 租来的；sent it — 豁出去干  
</note>

<note>
🎙️: Carlos, the team kept you out extra long—frustrated?  
🏎️ Carlos Sainz: Yeah, I’m decent at saving the tyres, but today we maybe lacked a bit of awareness on the weather.  

decent — 不错的；awareness — 警觉性  
</note>

<note>
🎙️: George, you clipped the wall and had to park it—what now?  
🏎️ George Russell: Gutted. The wall felt slick like ice; once you’re in, it’s game over.  

slick — 滑的；gutted — 极度沮丧的  
</note>
---
<note>
🎙️: Max, that last-lap move was wild!  
🏎️ Max Verstappen: Yeah, I saw the gap and went for it. I’m not going to let one mistake rent space in my head—done, gone.  

rent — 租用（在脑中“租用空间”比喻耿耿于怀）  
</note>

<note>
🎙️: You were stuck behind the safety car forever; how do you stay patient?  
🏎️ Lewis Hamilton: I just breathe, man. I picture the lap record living rent-free in my mind and keep pushing.  

rent-free — 免租金（比喻某事在脑中挥之不去）  
</note>

<note>
🎙️: Lando, you crossed the line P2—must feel good!  
🏎️ Lando Norris: Honestly, I’m somewhat shocked; I thought we were out of the points after that spin.  

somewhat — 有点，多少  
</note>

<note>
🎙️: You lost ten seconds in the pits—what happened?  
🏎️ Charles Leclerc: Roughly speaking, the gun jammed and that’s it, my win disappeared.  

roughly — 大致上  
</note>

<note>
🎙️: You’ve been chasing this victory for two years—how does it taste?  
🏎️ Daniel Ricciardo: I’m going to thoroughly enjoy every bite of tonight’s pizza, that’s for sure!  

thoroughly — 彻底地，十足地  
</note>

<note>
🎙️: You brushed the wall on lap forty—did it rattle you?  
🏎️ Valtteri Bottas: I wanted to erase the memory instantly, like clicking an eraser on a sketch.  

erase — 抹去；eraser — 橡皮  
</note>

<note>
🎙️: First win of the season—sum it up in one word?  
🏎️ Carlos Sainz: Incredible. Just… incredible.  

incredible — 难以置信的  
</note>

<note>
🎙️: The strategy call didn’t work—how are you feeling?  
🏎️ Pierre Gasly: I’m trying not to let the frustration boil over, but yeah, it stings.  

frustration — 沮丧  
</note>

<note>
🎙️: You tangled with your teammate and both retired—what now?  
🏎️ Esteban Ocon: I’ll call him tonight; no need to let one crash frustrate the whole season.  

frustrate — 使懊恼  
</note>
---
<note>
🎙️: Max, you just took the win—how does it feel?  
🏎️ Max Verstappen: Honestly, it’s a miracle the rain didn’t wash us away. I was desperate to keep the car on track, so yeah, pretty happy right now.  

miracle — 奇迹;desperate — 拼命的  
</note>

<note>
🎙️: Lewis, the team’s plan left you behind your teammate—any frustration?  
🏎️ Lewis Hamilton: A bit. I thought we could promote a bolder move, but I guess their wisdom saw it differently. We’ll talk later.  

promote — 推动;wisdom — 智慧  
</note>

<note>
🎙️: Lando, you had to retire early today—what happened?  
🏎️ Lando Norris: Yeah, some weird leakage under the car, nothing I could do. I’ll just sacrifice tonight’s ice-cream and hope next week tastes better.  

retire — 退赛;leakage — 泄漏;sacrifice — 牺牲  
</note>

<note>
🎙️: Charles, you clinched third in a super-close fight—thoughts?  
🏎️ Charles Leclerc: This track is always competitive; you breathe wrong and somebody’s past you. Glad we held on.  

competitive — 竞争激烈的  
</note>

<note>
🎙️: Daniel, any word before you officially announce your future plans?  
🏎️ Daniel Ricciardo: I’ll announce everything soon, but right now I’m just grateful for the boys in the garage—today was tough.  

announce — 宣布  
</note>
---
<note>
🎙️: Max, your early retirement shocked everyone—what happened out there?  
🏎️ Max Verstappen: The car just went silent. One second I’m racing, next second I’m parked. Retirement wasn’t my decision today, but we’ll bounce back.  

retirement — 退赛;decision — 决定;bounce back — 振作起来  
</note>

<note>
🎙️: Lewis, you’ve said music is central to your life. Does it compete with racing for your sole identity?  
🏎️ Lewis Hamilton: Racing is my heartbeat, but music keeps me curious. I don’t need one sole identity; I’m passionate about every note and every lap.  

central — 核心的;sole — 唯一的;identity — 身份;curious — 好奇的;passionate — 充满热情的  
</note>

<note>
🎙️: Lando, the rain seemed to fascinate you out there—were you actually having fun?  
🏎️ Lando Norris: Fun? Mate, I was sliding like on ice! But yeah, the chaos does fascinate me; it keeps the adrenaline pumping.  

fascinate — 使着迷;chaos — 混乱;adrenaline — 肾上腺素  
</note>

<note>
🎙️: Charles, after that last-lap mistake, any regrets?  
🏎️ Charles Leclerc: Tons. I was too greedy, and the wall paid the price. The fascination with pushing limits sometimes bites you.  

regrets — 遗憾;greedy — 贪心的;bites you — 让你吃亏  
</note>

<note>
🎙️: Daniel, you’ve always been the smiley guy. How do you keep that identity after a tough day?  
🏎️ Daniel Ricciardo: I figure nobody wants a grumpy Aussie. Staying positive is a decision I make every morning, even when the car’s moody.  

identity — 个性;grumpy — 脾气坏的;moody — 闹脾气的  
</note>
---
<note>
🎙️: You’ve said this win means everything—why?  
🏎️ Max Verstappen: It’s pure passion. I don’t just like racing, I obsess over every tiny detail; when it finally clicks, the relief is massive.  

passion — 热情;obsess — 痴迷;relief — 如释重负  
</note>

<note>
🎙️: The team told you to hold position behind your teammate—were you okay with that?  
🏎️ Lewis Hamilton: Honestly, I got a bit impatient on the radio, but I respect the bigger picture; you need tolerance to fight another day.  

impatient — 不耐烦;tolerance — 宽容;the bigger picture — 大局  
</note>

<note>
🎙️: You spun on lap one—what went through your head?  
🏎️ Lando Norris: I was so annoyed at myself, yet the stubborn side of me said, “Keep going, laugh later.” I smiled… eventually.  

annoyed — 恼火;stubborn — 倔的;eventually — 最终  
</note>

<note>
🎙️: You’ve collected model cars since you were five—still at it?  
🏎️ Charles Leclerc: It’s an obsession that keeps me calm; I line them up patiently after every race, like tiny trophies.  

obsession — 痴迷;patiently — 耐心地;trophies — 战利品  
</note>

<note>
🎙️: Your engineer kept reminding you to save fuel—did it drive you crazy?  
🏎️ Daniel Ricciardo: A little, but I stayed tolerant; if you let the voice in your ear turn into an obsession, you forget to race and just get cranky.  

tolerant — 包容的;obsession — 执念;cranky — 烦躁的  
</note>
---
<note>
🎙️: Lando, you spun on lap one—what happened?  
🏎️ Lando Norris: I hit a patch that felt super smelly, lost the rear, and the whole car just went “nope.” We’ll laugh about it later, I guess.  

smelly — 有怪味的;laugh — 笑  
</note>

<note>
🎙️: Max, second place again—are you getting annoyed?  
🏎️ Max Verstappen: A little, yeah. I gave it everything, but the safety-car timing was a pain. Still, no point crying; I’m an optimist—we’ll bounce back.  

annoy — 恼火;optimist — 乐观的人  
</note>

<note>
🎙️: Lewis, you had to park the car—how do you stay upbeat?  
🏎️ Lewis Hamilton: My crew’s commitment keeps my optimism alive. We’ll shift focus, work overnight, and come back stronger.  

commitment — 投入;optimism — 乐观;shift — 转移（注意力）  
</note>

<note>
🎙️: Charles, you were leading and then the rain hit—tough one?  
🏎️ Charles Leclerc: Heartbreaking. The back end just let go, I felt the car fall away. Still, a lot to learn; I stay optimistic for next week.  

fall — 跌落;a lot — 很多;optimistic — 乐观的  
</note>
---
<note>
🎙️: That last-lap overtake must feel huge right now.  
🏎️ Max Verstappen: It was decisive, no doubt. I saw the gap and just went for it—couldn’t afford to hesitate.  

decisive — 决定性的;afford — 承受得起（时间/风险）  
</note>

<note>
🎙️: You were shouting on the radio when the safety car came out. What happened?  
🏎️ Lando Norris: I was yelling because the rhythm was gone. You tap the brakes, the temps drop away, and suddenly everything feels weird.  

tap — 轻踩;away — （温度）掉得飞快  
</note>

<note>
🎙️: Second place after starting last—how do you sum that up?  
🏎️ Lewis Hamilton: Honestly, it’s the alternative story I needed. It’ll inspire the guys in the garage and certainly shows we never gave up.  

alternative — 另一种（剧本）;inspire — 激励;certainly — 当然  
</note>

<note>
🎙️: You and your teammate were side-by-side for ages; any tension?  
🏎️ Daniel Ricciardo: Nah, we respect the line. I’d alternate the inside, he’d go outside—just glad we both kept it clean.  

alternate — 交替使用;appreciate — 欣赏（对方干净驾驶）  
</note>

<note>
🎙️: The car stopped on the straight—what are you feeling right now?  
🏎️ Charles Leclerc: Frustrated, but every aspect of today will teach us something. I still appreciate the crowd staying loud for me.  

aspect — 方面;appreciate — 感激  
</note>
---
<note>
🎙️: Max, you just took the win—how does it feel?  
🏎️ Max Verstappen: Extremely good. We gained a lot of points today, and that’s the positive we needed.  

extremely — 极其;gained — 获得;positive — 积极的一面  
</note>

<note>
🎙️: Lewis, the rain made everything tricky—what was the biggest drawback?  
🏎️ Lewis Hamilton: Visibility was the fundamental issue; one small splash and you lose the line completely.  

drawback — 缺点;fundamental — 根本的  
</note>

<note>
🎙️: Lando, you and Oscar were side-by-side for ages—how do you stay calm?  
🏎️ Lando Norris: I just kept it sequential: breathe, turn, accelerate. It’s like parallel parking at 300 kph, mate!  

sequential — 按顺序的;parallel — 平行的  
</note>

<note>
🎙️: Charles, after that late spin, any quick self-evaluation?  
🏎️ Charles Leclerc: Overall, I messed up. I’ll watch the replay, learn, and come back stronger.  

evaluation — 评估;overall — 总体来说  
</note>
---
<note>
🎙️: Max, you lost the win after the last pit-stop. How do you feel?  
🏎️ Max Verstappen: I’m not happy, but I won’t attach blame to anyone. We’ll investigate what went wrong and come back stronger.  

attach blame — 归咎于;investigate — 调查  
</note>

<note>
🎙️: Lewis, you took the elevator up to the podium instead of the stairs—any reason?  
🏎️ Lewis Hamilton: Haha, my legs were toast after that wet race. The elevator felt like the only gainful move I made all afternoon.  

elevator — 电梯;stair — 楼梯;gainful — 有收益的  
</note>

<note>
🎙️: Lando, you retired on lap one. What happened?  
🏎️ Lando Norris: Someone spun, I had zero room, and my front wing went flying. No reservation about it—today was just rubbish.  

reservation — 保留意见  
</note>

<note>
🎙️: Charles, you climbed back to P5 after the early spin. How’d you keep calm?  
🏎️ Charles Leclerc: I told myself, “Retrieve the pace, one car at a time.” Staying patient was critical, and it paid off.  

retrieve — 找回;critical — 关键的  
</note>
---
`

export function formatContet() {
  const filterNotes = content.split(`\n---\n`).filter(Boolean)
  const notes: string[] = []
  for (const item of filterNotes) {
    notes.push(...extractNotes(item))
  }
  return notes.map((i) => {
    return i
    return '\n```\n' + i + '\n```\n'
  })
}

function extractNotes(text: string) {
  const re = /<note>\s*([\s\S]*?)\s*<\/note>/g // [\s\S] 支持匹配换行，? 为非贪婪
  const results = []
  let match
  while ((match = re.exec(text)) !== null) {
    const content = match[1]!.trim()
    results.push(content)
  }
  return results
}
